import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/navbar/Navbar";
import ClientOnly from "@/app/components/ClientOnly";
import Modal from "@/app/components/modals/Modal";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Interview',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <Navbar />
            <Modal actionLabel="Submit" isOpen title="Hello World!!!" />
        {children}
      </body>
    </html>
  )
}
